name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]  
    steps:
    - name: node-steup
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: npm build
      run: npm run build --if present
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWD: ${{secrets.DOCKER_PASSWD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWD

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag srinidhi2020/react-app

    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/react-app
